apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pdf
  labels:
    {{- include "docextractor.labels" . | nindent 4 }}
spec:
  accessModes: ["{{ .Values.storage.accessMode }}"]
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.pdfSize }}
