"""add firecrawl_job_id and current_phase to extraction_runs

Revision ID: 6601fe70d971
Revises: a1b2c3d4e5f6
Create Date: 2026-06-16 20:00:16.892986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6601fe70d971'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_runs', sa.Column('firecrawl_job_id', sa.String(length=128), nullable=True))
    op.add_column('extraction_runs', sa.Column('current_phase', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_runs', 'current_phase')
    op.drop_column('extraction_runs', 'firecrawl_job_id')
    # ### end Alembic commands ###
